### ISSUE TITLE
Error installing plug-in for matomo

### ISSUE THREAD

**Issue by zhaoshilong0221** [Findus23/plugin-LanguageToogle#1]
I deployed matomo on my server, and selected the non installed plug-ins in the mall of plug-ins for installation. He will jump to the phase of confirming the password. When I input the password, there will be an error. The error is: "the security of this form cannot be verified." However, I did not find the exact solution. Please give me the answer. Thank you.
![image](https://user-images.githubusercontent.com/56672178/67734455-1ba09000-fa3c-11e9-80ed-fb40b9da1597.png)

**Comment by Findus23** [comment]
Hi,

This issue is independent of this plugin and occurs sometimes in Matomo (I unfortunatly can't reproduce it reliably). You can try again by going back to the Marketplace page, reloading the page and installing again which should then work.
