### ISSUE TITLE
Remove from settings in case of non-super-user

### ISSUE THREAD

**Issue by heurteph-ei** [Findus23/plugin-LanguageToogle#8]
As the Toggle is only displayed for super user (is there any reason?), the setting should be available only in user setting of super users...

**Comment by Findus23** [comment]
> is there any reason?

That's a really great question. It has been 5 years and I completely forgot why I was doing it.
I don't really feel safe dropping the restrictions as I don't fully understand the reason, so I quickly added a check to hide the setting from non-superusers (hopefully): b8a702b
